from .proto_kasanic.phonology import ProtoKasanicPhonologyTests
from .proto_kasanic.transcribe import TranscriptionTests
from .proto_kasanic.morphology import ProtoKasanicMorphologyTests
from .proto_kasanic.generate import PKGenerationTests
from .lauvinko.phonology import LauvinkoPhonologyTests
from .lauvinko.diachronic import LauvinkoDiachronicTests
from .lauvinko.transcribe import LauvinkoTranscriptionTests
from .dictionary.entry import DictEntryTests
from .dictionary.dictionary import DictionaryTests
